# version: "3.9"

# services:
#   app:
#     build:
#       context: .
#     image: nextjs-app
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: development
#     volumes:
#       - ./src:/app/src:rw # Mount the source code for live development
#       - /app/node_modules # Ensure node_modules aren't overwritten by the bind mount

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
